### ISSUE TITLE
POWER_LOSS_PIN  ?

### ISSUE THREAD

**Issue by gsuresh2u** [FLYmaker/FLYF407ZG#18]
i want to enable Power Loss recovery after power loss
Power cut in my area is very horrible, so, without using Power Loss recovery, its so much of Filament waste
I searched in all places in this , but not found any POWER_LOSS_PIN  no
Please someone provide me PIN no 
Or is there any other external devise to use with this controller to use Power loss recovery ?
Please help

**Comment by FLYmaker** [comment]
#define POWER_LOSS_PIN         PA3//Filament runout interface
OR
#define POWER_LOSS_PIN         PC14//// Z3_PIN

**Comment by gsuresh2u** [comment]
Ok, Thanks, i will try
