### ISSUE TITLE
Connection Problem with Pronterface 

### ISSUE THREAD

**Issue by gsuresh2u** [FLYmaker/FLYF407ZG#23]
Hi, i tried to connect with Pronterface
Its showing connected, but giving error 
`Starting USB host...Revision register appears incorrect on MAX3421e initialization. Got 255 failed`
![Pronterface Error](https://user-images.githubusercontent.com/39871361/88479178-ded1dd00-cf6a-11ea-880e-1e365f831d17.jpg)

i already installed USB drivers, in Devise manager, its showing fine
Please check the attached images
![COM Port](https://user-images.githubusercontent.com/39871361/88479171-cfeb2a80-cf6a-11ea-901a-71de6d62e722.jpg)

enabled Software SPI and changed pins and added Jumpers for SPI mode
![Jumpers](https://user-images.githubusercontent.com/39871361/88479105-88fd3500-cf6a-11ea-86d5-0772eb7793e2.JPG)

and is my Drivers Orientation is Correct same as in the below image ?
![Drivers](https://user-images.githubusercontent.com/39871361/88479142-a7633080-cf6a-11ea-9b13-10ae5b9db2c3.JPG)

I have connected only Board, not connected anything for testing
(as my printer is Big , its unable to move to indoor)

**Comment by FLYmaker** [comment]
Qǐng bǎ nǐ de gùjiàn fā shànglái, bìngqiě tmc2209 shì bùnéng shǐyòng spi de
28/5000
Please send your firmware up, and tmc2209 cannot use spi

**Comment by FLYmaker** [comment]
Please send your firmware up, and tmc2209 cannot use spi

**Comment by gsuresh2u** [comment]
Sir, here i attached my Configurations and pins

[pins_FLYF407ZG.zip](https://github.com/FLYmaker/FLYF407ZG/files/4977702/pins_FLYF407ZG.zip)

[platformio.zip](https://github.com/FLYmaker/FLYF407ZG/files/4977703/platformio.zip)
[Configurations.zip](https://github.com/FLYmaker/FLYF407ZG/files/4977704/Configurations.zip)

**Comment by gsuresh2u** [comment]
[firmware.zip](https://github.com/FLYmaker/FLYF407ZG/files/4977744/firmware.zip)

**Comment by FLYmaker** [comment]
Do you want to use a USB flash drive? That's why this feature is turned on?

**Comment by gsuresh2u** [comment]
Yes, want to usb flash drive

**Comment by FLYmaker** [comment]
#define USE_UHS3_USB        
Open this to try

**Comment by FLYmaker** [comment]
The USB port of the motherboard can also use a USB flash drive, but I haven't tested it yet. I will test it shortly

**Comment by gsuresh2u** [comment]
When i enable #define USE_UHS3_USB, its giving compile errors, 
and tried with disabling #define USB_FLASH_DRIVE_SUPPORT 
and uploaded firmware
Now, its connected fine

**Comment by gsuresh2u** [comment]
can i need to disable software SPI in marlin ?
i have changed Jumpers for TMC2209 to UART mode

**Comment by FLYmaker** [comment]
Yes, you need to close it and use uart

**Comment by gsuresh2u** [comment]
Ok, Thanks for support
