### ISSUE TITLE
Need clarification of Connection of Stepper motor

### ISSUE THREAD

**Issue by gsuresh2u** [FLYmaker/FLYF407ZG#25]
Sir, After long time, today i received Stepper motors
not found any wiring diagram for pins on board
here is my motor winding
![Motor Winding](https://user-images.githubusercontent.com/39871361/89145922-c9167600-d56f-11ea-95f4-f85f598e9ba8.jpg)

And i am confused to connect mother board pins
Can you please clarify the connection to which pin i have to connect ?
![Pins Motor Connection](https://user-images.githubusercontent.com/39871361/89145962-e8150800-d56f-11ea-8c8c-e66ea4ce81aa.jpg)

**Comment by FLYmaker** [comment]
![TJK7 2HTP_EPBRG}RLQ}3(O](https://user-images.githubusercontent.com/49380822/89148679-1a812e00-d58d-11ea-8678-9fe10727734f.png)
The motherboard needs to be plugged in a driver (like 4988) before it can be used

**Comment by gsuresh2u** [comment]
Thank you
