### ISSUE TITLE
How to connect TFT70 V3.0? 

### ISSUE THREAD

**Issue by gsuresh2u** [FLYmaker/FLYF407ZG#27]
Today I received TFT70 V3.0
It has 5V input pins to power up screen 
But I have not found any 5V output pins in this board 
Found 3 power output ports in bottom right side
But in description it's saying they are 12V/24V
My input is 12V with 400W PSU
From where I can take 5V output?
Here I am attaching photos 
![Screenshot_20200827-123550](https://user-images.githubusercontent.com/39871361/91409119-9572f700-e862-11ea-8d7d-7cd6448bfc15.jpg)
![IMG-20200824-WA0003](https://user-images.githubusercontent.com/39871361/91409389-f7cbf780-e862-11ea-8b35-32e653ac0966.jpeg)

**Comment by FLYmaker** [comment]
![W@8W0$}BKB KSHQKHPQ{Y`8](https://user-images.githubusercontent.com/49380822/91409861-a0388680-e878-11ea-8243-281f53693cb5.png)

**Comment by FLYmaker** [comment]
[video.zip](https://github.com/FLYmaker/FLYF407ZG/files/5134705/video.zip)

**Comment by FLYmaker** [comment]
This is our own 7-inch screen, you can take a look

**Comment by gsuresh2u** [comment]
OK, thanks
