### ISSUE TITLE
Anything for the "External drive expansion interface"

### ISSUE THREAD

**Issue by dixi83** [FLYmaker/FLYF407ZG#33]
Hi There,

Is there any hardware for the "External drive expansion interface"? 

This one:
![Untitled](https://user-images.githubusercontent.com/10693808/104105651-e3d3e000-52af-11eb-8333-fc40a085e3dd.png)

The thing is I maybe want 2 extra drives in the future.... I know there is also the BTT GTR but this is a shitty designed board with no support. This one looks far more promising.

**Comment by jaysuk** [comment]
Nothing has been designed yet as far as I'm aware
